osx_image: xcode10.2
language: objective-c
cache: cocoapods
before_install:
- gem install fastlane
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
script:
- fastlane scan --project SwiftyTesseract/SwiftyTesseract.xcodeproj/ --scheme SwiftyTesseract
- pod spec lint